-- =====================================================
-- Lock down order-attachments Storage bucket
-- Audit finding (Critical): bucket was created with `public = true`
-- (migration 20260403_tracking_tables.sql:150), which exposes every
-- object at https://<project>.supabase.co/storage/v1/object/public/
-- order-attachments/<path>. URLs are guessable if filenames follow a
-- predictable pattern (seq/uuid) — enumerating a few thousand paths
-- exfiltrates every repair photo, bespoke signature, and customer
-- document across every tenant.
--
-- Fix: flip bucket to private. Reads now require either a signed URL
-- (generated server-side) or an authenticated user whose tenant owns
-- the object. Storage RLS policies replaced accordingly.
--
-- Caller-side changes: the /track/[id] page + CustomerAttachments
-- component now call a `signOrderAttachmentUrl()` helper that turns
-- the raw file_url into a 1-hour signed URL. Existing URLs in the DB
-- don't need migration — the raw URL is still the source of truth,
-- just served via signed access now.
-- =====================================================

-- 1. Flip bucket to private ----------------------------------------------
UPDATE storage.buckets SET public = false WHERE id = 'order-attachments';

-- 2. Replace the permissive "Public read for order attachments" policy --
DROP POLICY IF EXISTS "Public read for order attachments" ON storage.objects;

-- Authenticated users can read objects their tenant owns. This path
-- is used by the in-app CustomerAttachments component (runs under the
-- authed user client). The track page uses the service role which
-- bypasses RLS anyway.
DROP POLICY IF EXISTS "Authed tenant read order attachments" ON storage.objects;
CREATE POLICY "Authed tenant read order attachments" ON storage.objects
  FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'order-attachments'
    AND EXISTS (
      SELECT 1 FROM public.order_attachments oa
      WHERE oa.file_url LIKE '%/' || storage.objects.name
        AND oa.tenant_id IN (SELECT tenant_id FROM public.users WHERE id = auth.uid())
    )
  );

-- Anon role: no SELECT. Public customers who need to view attachments
-- go through signed URLs generated by the service-role track page.

-- 3. Upload policy unchanged (authenticated only) -------------------------
-- Already covered by the existing "Authenticated upload for order attachments"
-- policy from 20260403_tracking_tables.sql:162.

COMMENT ON POLICY "Authed tenant read order attachments" ON storage.objects IS
  'Replaces prior public bucket read. Bucket is private; authed users see only their tenant''s objects. Public /track page uses service role.';
