-- M-10 Phase 1 (desktop-Opus): replace enumerable sequential
-- passport_uid (= identity_number stringified, starting at 100000001
-- per migration 20260330_global_passport_identity.sql) with an
-- unguessable public_uid (UUID v4, generated by crypto.randomUUID()
-- in app code at insert time).
--
-- Threat model: external actor iterates 100000001, 100000002, ...
-- through /verify/[uid] (public page) to enumerate every passport
-- across every tenant. Returns title, jewellery_type, metal/stone
-- specs, owner_name. Privacy + competitive-intelligence leak.
--
-- Phase 1 (this migration + bundled code changes):
--   1. ADD public_uid TEXT NULL UNIQUE
--   2. UNIQUE INDEX for verify-endpoint lookups
--   3. Backfill via scripts/backfill-passport-public-uids.ts
--      post-deploy (NOT applied by this migration — kept idempotent
--      so re-applying is safe and the 90-day soak window is owner-
--      controlled).
--
-- Phase 2 (90 days post-deploy, separate PR): sunset legacy
-- passport_uid + identity_number lookups based on audit-log volume.
--
-- Why TEXT not UUID: the column stores the string form of UUID v4
-- (e.g. "9f7e8b62-..."). Using TEXT means we can later widen the
-- format (add a non-UUID prefix, change to ULID, etc.) without
-- another migration. The UNIQUE constraint enforces collision
-- safety regardless of format.

ALTER TABLE public.passports
  ADD COLUMN IF NOT EXISTS public_uid TEXT;

-- Partial unique index: enforces uniqueness only on non-NULL values.
-- Lets us land the column ahead of the backfill without violating
-- uniqueness for the brief window before each row gets its own
-- public_uid.
CREATE UNIQUE INDEX IF NOT EXISTS passports_public_uid_unique
  ON public.passports (public_uid)
  WHERE public_uid IS NOT NULL;

COMMENT ON COLUMN public.passports.public_uid IS
  'M-10: unguessable UUID v4 used as the public share/verify '
  'identifier. Replaces the enumerable identity_number-based '
  'passport_uid for new passports. Legacy passport_uid lookups '
  'remain supported through 2026-08-05 (90 days post-deploy) for '
  'physical QR/NFC compat, then sunset.';

-- Audit log of every public verify hit on a legacy
-- passport_uid / identity_number (NOT public_uid). Drives the
-- sunset decision at 2026-08-05: if legacy lookups have decayed
-- to ~0/day, hard 404 the legacy ladder.
CREATE TABLE IF NOT EXISTS public.passport_legacy_lookups (
  id BIGSERIAL PRIMARY KEY,
  passport_id UUID NOT NULL REFERENCES public.passports(id) ON DELETE CASCADE,
  tenant_id UUID NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  lookup_form TEXT NOT NULL CHECK (lookup_form IN ('legacy_nxp', 'legacy_numeric')),
  ip_hash TEXT,
  user_agent TEXT,
  looked_up_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS passport_legacy_lookups_tenant_at
  ON public.passport_legacy_lookups (tenant_id, looked_up_at DESC);

CREATE INDEX IF NOT EXISTS passport_legacy_lookups_at
  ON public.passport_legacy_lookups (looked_up_at DESC);

COMMENT ON TABLE public.passport_legacy_lookups IS
  'M-10: per-hit audit of legacy passport-id verify lookups. '
  'Sunset decision at 2026-08-05 reads daily volume from this '
  'table — if traffic has decayed to ~0/day, the legacy ladder '
  'is removed in Phase 2 PR.';

-- Tenant-scoped RLS: tenant owners + the platform admin can read
-- their own audit rows. Inserts are server-only (admin client).
ALTER TABLE public.passport_legacy_lookups ENABLE ROW LEVEL SECURITY;

CREATE POLICY passport_legacy_lookups_select_own_tenant
  ON public.passport_legacy_lookups
  FOR SELECT
  USING (
    tenant_id IN (
      SELECT tenant_id FROM public.users WHERE id = auth.uid()
    )
  );
